
services:
  db:
    image: mysql:8.0
    container_name: mautic_db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MAUTIC_DB_NAME}
      MYSQL_USER: ${MAUTIC_DB_USER}
      MYSQL_PASSWORD: ${MAUTIC_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${MAUTIC_DB_USER}", "-p${MAUTIC_DB_PASSWORD}"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - mautic_net

  mautic:
    image: mautic/mautic:v5-apache # v6 ainda está em beta instável, recomendo v5
    container_name: mautic
    depends_on:
      db:
        condition: service_healthy
    environment:
      MAUTIC_DB_HOST: db
      MAUTIC_DB_NAME: ${MAUTIC_DB_NAME}
      MAUTIC_DB_USER: ${MAUTIC_DB_USER}
      MAUTIC_DB_PASSWORD: ${MAUTIC_DB_PASSWORD}
      MAUTIC_URL: ${MAUTIC_URL}
    volumes:
      - mautic_data:/var/www/html # Persistência total
    networks:
      - mautic_net
      - proxy_default
    ports:
      - "8082:80"

networks:
  mautic_net:
  proxy_default:
    external: true

volumes:
  db_data:
  mautic_data:
